### ISSUE TITLE
Save Function is not Working

### ISSUE THREAD

**Issue by ccthomas** [Markfast/Markfast#3]
Ignore Console Log (Debugging Converter: List)
<img width="814" alt="screen shot 2018-03-31 at 6 11 46 pm" src="https://user-images.githubusercontent.com/12040399/38168354-3a2034e8-350f-11e8-9626-759d28c12790.png">

**Comment by BenDMyers** [comment]
Fixed as of c27d3d8e57902480e62317a152a3658001cb2eb9.
